import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/lib/useAuth';

import { CartProvider } from '@/lib/cartContext';
import { CheckoutProvider } from '@/lib/checkoutContext';
import { Header } from '@/components/header/header';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>
          <CartProvider>
            <CheckoutProvider>
              <Header />
              <main className="lg:max-w-[1330px] lg:my-0 lg:mx-auto px-4 lg:px-0">
                {children}
              </main>
            </CheckoutProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
